# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: proxmox-cloud-controller-manager

builds:
  - id: proxmox-cloud-controller-manager
    dir: ./cmd/proxmox-cloud-controller-manager
    binary: proxmox-cloud-controller-manager
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X k8s.io/component-base/version.gitVersion={{ .Version }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

snapshot:
  version_template: edge

changelog:
  disable: true

dockers_v2:
  - id: docker
    flags:
      - --target=goreleaser
    images:
      - "ghcr.io/sergelogvinov/{{ .ProjectName }}"
    tags:
      - "{{ if not .IsSnapshot }}v{{.Version}}{{ else }}edge{{ end }}"
      - edge
    platforms:
      - linux/amd64
      - linux/arm64
    annotations:
      org.opencontainers.image.name: "{{ .ProjectName }}"
      org.opencontainers.image.description: "Proxmox Cloud Controller Manager"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.source: "https://github.com/sergelogvinov/{{ .ProjectName }}"
      org.opencontainers.image.url: "{{ .GitURL }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      io.artifacthub.package.readme-url: "https://raw.githubusercontent.com/sergelogvinov/{{ .ProjectName }}/main/README.md"
      io.artifacthub.package.license: "Apache-2.0"

docker_signs:
  - id: docker
    cmd: cosign
    args:
      - sign
      - "--yes"
      - "${artifact}"
    output: true

archives:
  - id: proxmox-cloud-controller-manager
    formats: ["gz"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sigstore.json"
    cmd: cosign
    args:
      - sign-blob
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
    output: true
